# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib C:/Users/Elitebook/Desktop/code/FPGA/RISC_V/Processor/Processor.srcs/sources_1/new/RegisterFile.v
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Elitebook/Desktop/code/FPGA/RISC_V/Processor/Processor.cache/wt [current_project]
set_property parent.project_dir C:/Users/Elitebook/Desktop/code/FPGA/RISC_V/Processor [current_project]
catch { write_hwdef -file RegisterFile.hwdef }
synth_design -top RegisterFile -part xc7a35tcpg236-1
write_checkpoint RegisterFile.dcp
report_utilization -file RegisterFile_utilization_synth.rpt -pb RegisterFile_utilization_synth.pb
